### ISSUE TITLE
SparkDensityTree Hisograms

### ISSUE THREAD

**Issue by gallenaxel** [giuliaripellino/GOAR-ML-Project#6]
Create histogram as outlined in SparkDensityTree-Introduction.scala ([link](https://github.com/lamastex/SparkDensityTree-examples/blob/main/notebooks/SparkDensityTree-Introduction.scala))

**Comment by olgeet** [comment]
- [ ] Understand output

**Comment by olgeet** [comment]
- [ ] Plot output using the visualisation tools in SparkDensityTree2D-LineMixture

**Comment by olgeet** [comment]
- [ ] Write to Raaz

**Comment by olgeet** [comment]
Migrate to separate issues
